# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160730_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 8, 28, 29, 454234, tzinfo=utc)),
        ),
    ]
